language: java
jdk:
- openjdk11
- 
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build --debug"
notifications:
  email:
    recipients:
    - jjy5349@naver.com
before_install:
- openssl aes-256-cbc -K $encrypted_a6d8b8556fee_key -iv $encrypted_a6d8b8556fee_iv
  -in application.yml.enc -out src/main/resources/application.yml -d
