language: java
jdk:
- openjdk11
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - jjy5349@naver.com

before_install:
- openssl aes-256-cbc -K $encrypted_1b7250f06fd5_key -iv $encrypted_1b7250f06fd5_iv
  -in covid19vaccinereview.tar.enc -out covid19vaccinereview.tar -d
