language: java
jdk:
- openjdk11
- 
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - jjy5349@naver.com
before_install:
- openssl aes-256-cbc -K $encrypted_a6d8b8556fee_key -iv $encrypted_a6d8b8556fee_iv
  -in application.yml.enc -out src/main/resources/application.yml -d
- openssl aes-256-cbc -K $encrypted_c68d8d92dff4_key -iv $encrypted_c68d8d92dff4_iv
  -in application-port-8082.yml.enc -out src/main/resources/application-port-8082.yml
  -d
- openssl aes-256-cbc -K $encrypted_2f64d08ed525_key -iv $encrypted_2f64d08ed525_iv
  -in application-port-8081.yml.enc -out src/main/resources/application-port-8081.yml
  -d
- openssl aes-256-cbc -K $encrypted_961712aa765b_key -iv $encrypted_961712aa765b_iv
  -in application-real.yml.enc -out src/main/resources/application-real.yml -d
- openssl aes-256-cbc -K $encrypted_4c414bd4c38d_key -iv $encrypted_4c414bd4c38d_iv
  -in application-local.yml.enc -out src/main/resources/application-local.yml -d
before_deploy:
- mkdir -p before-deploy
- cp scripts/*.sh before-deploy/
- cp appspec.yml before-deploy/
- cp build/libs/*.jar before-deploy/
- cd before-deploy && zip -r before-deploy *
- cd ../ && mkdir -p deploy
- mv before-deploy/before-deploy.zip deploy/covid19vaccinereview.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: covid19vaccinereview
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: covid19vaccinereview
  key: covid19vaccinereview.zip
  bundle_type: zip
  application: covid19vaccinereview
  deployment_group: covid19vaccinereview-group
  region: ap-northeast-2
  wait-until-deployed: true
dd:
- openssl aes-256-cbc -K $encrypted_961712aa765b_key -iv $encrypted_961712aa765b_iv
  -in application-real.yml.enc -out src/main/resources/application-real.yml -d
- openssl aes-256-cbc -K $encrypted_4c414bd4c38d_key -iv $encrypted_4c414bd4c38d_iv
  -in application-local.yml.enc -out src/main/resources/application-local.yml -d
- openssl aes-256-cbc -K $encrypted_a6d8b8556fee_key -iv $encrypted_a6d8b8556fee_iv
  -in application.yml.enc -out src/main/resources/application.yml -d
