version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/step3/zip/
    overwirte: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: before.sh
      timeout: 120
      runas: ubuntu

  AfterInstall:
    - lcoation: stop.sh
      timeout:  120
      runas:  ubuntu

  ApplicationStart:
    - location: start.sh
      timeout:  120
      runas: ubuntu

  ValidateService:
    - location: health.sh
      timeout: 120
      runas: ubuntu
