version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/zip/scripts/
    overwirte: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 120
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 120
      runas: ubuntu
  ValidateService:
    - location: health.sh
      timeout: 120
      runas: ubuntu