version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/step3/zip/
    overwirte: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - lcoation: stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: health.sh
      timeout: 60
      runas: ubuntu