# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ master ]

env:
  JASYPT_PASSWORD: ${secret.JASYPT_PASSWORD}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 체크아웃 Github Action
      uses: actions/checkout@v2
      
    - name: JDK 11 설치
      uses: actions/setup-java@v2
      with:
        java-version: 11
    
    - name: gradlew 실행 권한 부여
      run: chmod +x gradlew
      shell: bash
    
    - name: Build with Gradle
      run: ./gradlew clean build
      shell: bash
    
    - name: Make zip file 
      run: zip -r ./build.zip
      shell: bash 
      
