# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-18.04
  
    env:
      JASYPT_PASSWORD : ${{ secrets.JASYPT_PASSWORD }}
    
    steps:
    - name: 테스트
      run: echo "$JASYPT_PASSWORD 입니다"
        
    - name: 체크아웃 Github Action
      uses: actions/checkout@v2
      
    - name: JDK 11 설치
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: gradlew 실행 권한 부여
      run: chmod +x gradlew
      shell: bash
    
    - name: Build with Gradle
      run: ./gradlew clean build --info
      shell: bash

    - name: zip 파일 생성
      run: zip -r ./$GITHUB_SHA.zip .
      shell: bash

    - name: AWS 자격 증명
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: S3 업로드
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.S3_BUCKET_NAME }}/$GITHUB_SHA.zip

    - name: CodeDeploy 배포
      run: aws deploy create-deployment --application-name Github-Actions-Deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name Github-Actions-Group --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=$GITHUB_SHA.zip

